### ISSUE TITLE
[FEATURE] 로그인 / 회원가입 api 구현 및 연결

### ISSUE THREAD

**Issue by j2h30728** [wanted-pre-onboarding-team-9/pre-onboarding-10th-1-9#10]
### 🤸 Describe the required feature

로그인 / 회원가입 api 구현 및 연결

### 🏊 Todo

- [x] 로그인 / 회원가입 api 구현
- [x] 로그인 / 회원가입 페이지에서 api 연결
- [x]  로그인 / 회원가입 api 에러 메시지 포맷팅

### 💬 Additional information

- 모호한 서버 에러메시지를 포맷팅 할 것

**Comment by SangWoo9734** [comment]
관련 PR 종료되어서 해당 이슈도 종료하겠습니다!
