### ISSUE TITLE
[FEATURE] GitHub Actions를 이용한 lint 검사

### ISSUE THREAD

**Issue by ohcmadah** [wanted-pre-onboarding-team-9/pre-onboarding-10th-1-9#18]
### 🤸 Describe the required feature
GitHub Actions를 이용하여 Pull Request가 생성되었을 때, `eslint --cache --max-warnings=0 '**/*.{ts,tsx}'` 명령어를 실행한다.
lint를 통과하지 못할 경우 `main`에 merge를 할 수 없도록 설정한다.

### 🏊 Todo

- [x] `.github` 폴더 내에 `workflows` 폴더 생성
- [x] `lint.yml`에 워크플로우 작성
- [x] Repository Settings > Branches > Branch protection rules > status checks 활성화

### 💬 Additional information
Git Hook을 이용해 `eslint --cache --max-warnings=0 '**/*.{ts,tsx}'`를 통과해야 Push를 할 수 있게 되어있었으나, 코드 공유 측면에서 불편함이 발생하여 `--max-warnings=0` 옵션을 제거하기로 결정하였다. 다만, `main`에는 warning이 존재하지 않는 상태로 유지하고 싶어 도입하기로 결정하였다.
