### ISSUE TITLE
[DOCS] README 작성

### ISSUE THREAD

**Issue by sena-22** [wanted-pre-onboarding-team-9/pre-onboarding-10th-1-9#22]
### 🤸 Describe the required feature
README 작성
### 🏊 Todo

- [x] 프로젝트 소개
- [x] 프로젝트 실행 방법
- [x] Beat Practice 설명
- [x] 기술 스택
- [x] contributors
- [x] 배포링크 or 데모영상 
- [x] test 계정
