### ISSUE TITLE
[FEATURE] 로그아웃 기능 구현

### ISSUE THREAD

**Issue by SangWoo9734** [wanted-pre-onboarding-team-9/pre-onboarding-10th-1-9#27]
### 🤸 Describe the required feature

Todo List 내 로그아웃 기능을 추가합니다.

### 🏊 Todo

- [x] 로그아웃 기능 추가
    - [x] 로그아웃시 토큰 제거
    - [x] 로그아웃시 메인 페이지로 이동

**Comment by SangWoo9734** [comment]
관련 PR 종료로 이번 이슈 종료하겠습니다.
