### ISSUE TITLE
프로젝트 세팅

### ISSUE THREAD

**Issue by sena-22** [wanted-pre-onboarding-team-9/pre-onboarding-10th-1-9#3]
### 🤸 Describe the required feature
과제 1 프로젝트 세팅
### 🏊 Todo

- [x] 패키지 설치
- [x] 레포지토리 설정
- [x] 폴더 & 라우터 세팅
- [x] lint & prettier & husky 적용
- [x] 모듈 작성(localstorage,token)
- [x] API 설정
