### ISSUE TITLE
[FEATURE] 프로젝트 세팅관련 피드백 반영

### ISSUE THREAD

**Issue by SangWoo9734** [wanted-pre-onboarding-team-9/pre-onboarding-10th-1-9#7]
### 🤸 Describe the required feature
프로젝트 세팅 후 피드백을 토대로 일부 코드를 수정합니다.

### 🏊 Todo
- [x] eslint 규칙 추가
    - [x] "react/jsx-uses-react": "off"
    - [x] "react/react-in-jsx-scope": "off"
- [x] prettier endOfLine 옵션 삭제
- [x] api/index.ts 파일 내 불필요한 주석 제거
- [x] src/routes/Auth.tsx 내 가독성 향상을 위한 빈 라인 추가
- [x] src/utiles/index.ts 파일 삭제 및 import 관련 코드라인 수정
